export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}

export const userConstants = {
    USER_REG_REQUEST: 'USER_REG_REQUEST',
    USER_REG_SUCCESS: 'USER_REG_SUCCESS',
    USER_REG_FAILURE: 'USER_REG_FAILURE'
}

export const categoryConstants = {
    GET_CATEGORIES_REQUEST: 'GET_CATEGORIES_REQUEST',
    GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
    GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE',
    ADD_CATEGORY_REQUEST:'ADD_CATEGORY_REQUEST',
    ADD_CATEGORY_SUCCESS:'ADD_CATEGORY_SUCCESS',
    ADD_CATEGORY_FAILURE:'ADD_CATEGORY_FAILURE',
    UPDATE_CATEGORY_REQUEST: 'UPDATE_CATEGORY_REQUEST',
    UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
    UPDATE_CATEGORY_FAILURE: 'UPDATE_CATEGORY_FAILURE',
    DELETE_CATEGORY_REQUEST: 'DELETE_CATEGORY_REQUEST',
    DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
    DELETE_CATEGORY_FAILURE: 'DELETE_CATEGORY_FAILURE'
}

export const productConstants = {
    GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
    GET_ALL_PRODUCT_REQUEST: 'GET_ALL_PRODUCT_REQUEST',
    GET_ALL_PRODUCT_SUCCESS: 'GET_ALL_PRODUCT_SUCCESS',
    GET_ALL_PRODUCT_FAILURE: 'GET_ALL_PRODUCT_FAILURE',
    ADD_PRODUCT_REQUEST:'ADD_PRODUCT_REQUEST',
    ADD_PRODUCT_SUCCESS:'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_FAILURE:'ADD_PRODUCT_FAILURE',
    DELETE_PRODUCT_BY_ID_REQUEST:'DELETE_PRODUCT_BY_ID_REQUEST',
    DELETE_PRODUCT_BY_ID_SUCCESS:'DELETE_PRODUCT_BY_ID_SUCCESS',
    DELETE_PRODUCT_BY_ID_FAILURE:'DELETE_PRODUCT_BY_ID_FAILURE'

}

export const initialDataConstants = {
    GET_INIT_DATA_REQUEST: 'GET_INIT_DATA_REQUEST',
    GET_INIT_DATA_SUCCESS: 'GET_INIT_DATA_SUCCESS',
    GET_INIT_DATA_FAILURE: 'GET_INIT_DATA_FAILURE'
}

export const pageConstants = {
    CREATE_PAGE_REQUEST: 'CREATE_PAGE_REQUEST',
    CREATE_PAGE_SUCCESS: 'CREATE_PAGE_SUCCESS',
    CREATE_PAGE_FAILURE: 'CREATE_PAGE_FAILURE'
}

export const orderConstants = {
    GET_ORDER_REQUEST: 'GET_ORDER_REQUEST',
    GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS',
    GET_ORDER_FAILURE: 'GET_ORDER_FAILURE',

    UPDATE_ORDER_REQUEST: 'UPDATE_ORDER_REQUEST',
    UPDATE_ORDER_SUCCESS: 'UPDATE_ORDER_SUCCESS',
    UPDATE_ORDER_FAILURE: 'UPDATE_ORDER_FAILURE',
    
    
}